### ISSUE TITLE
Additional peak equations

### ISSUE THREAD

**Issue by zunzun** [xaratustrah/curve-fitting#1]
I have over 50 peak equations coded in Python 2 and 3 on GitHub, you might be interested to review them.

Python 2:
https://github.com/zunzun/pyeq2/blob/master/Models_2D/Peak.py

Python 3:
https://github.com/zunzun/pyeq3/blob/master/Models_2D/Peak.py

James, email zunzun AT zunzun.com

**Comment by xaratustrah** [comment]
@zunzun wow! indeed it is a great collection. I will have a more detailed look. Thanks for the notice!
